pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo '========Building A========'
            }
        }
        stage('Test') {
            steps {
                echo '========Testing A========'
            }
        }
        stage('Deploy') {
            steps {
                echo '========Executing A========'
            }
        }
    }
}
